import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.awt.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class GAS extends javax.swing.JFrame {

    /**
     * Creates new form GAS
     */
    public GAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_holder = new javax.swing.JTabbedPane();
        panel_home = new javax.swing.JPanel();
        panel_home_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_time = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        button_home_pengguna = new java.awt.Button();
        button_pembayaran_home = new java.awt.Button();
        button_home_barang = new java.awt.Button();
        button_home_pengaturan = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GAS"); // NOI18N
        setPreferredSize(new java.awt.Dimension(975, 600));
        setResizable(false);

        tab_holder.setName("tabHolder"); // NOI18N
        tab_holder.setPreferredSize(new java.awt.Dimension(975, 600));

        panel_home_header.setBackground(new java.awt.Color(238, 77, 45));
        panel_home_header.setPreferredSize(new java.awt.Dimension(975, 200));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOKO GAS");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Made By");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("13521051 Manuella Ivana Uli Sianipar");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("13521053 Athif Nirwasito");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("13521115 Shelma Salsabila");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("13521165 Reza Pahlevi Ubaidillah");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));

        Thread thread = new Thread(() -> {
            while (true) {
                Date daten = new Date();
                SimpleDateFormat formatter1 = new SimpleDateFormat("dd-MM-yyyy");
                SimpleDateFormat formatter2 = new SimpleDateFormat("HH:mm:ss");

                String date = formatter1.format(daten);
                String time = formatter2.format(daten);
                label_time.setText("<html>" + time + "<br/>" + date + "</html>");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    System.out.println("Interrupted Exception");
                }
            }
        });
        thread.start();
        label_time.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("13521076 Moh. Aghna Maysan Abyan");

        javax.swing.GroupLayout panel_home_headerLayout = new javax.swing.GroupLayout(panel_home_header);
        panel_home_header.setLayout(panel_home_headerLayout);
        panel_home_headerLayout.setHorizontalGroup(
            panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_home_headerLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_home_headerLayout.createSequentialGroup()
                            .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_home_headerLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_home_headerLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(156, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_home_headerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel7)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_home_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226)
                .addComponent(label_time, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panel_home_headerLayout.setVerticalGroup(
            panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_home_headerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(label_time, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_home_headerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_home_headerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_home_headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_home_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_home_pengguna.setBackground(new java.awt.Color(255, 51, 0));
        button_home_pengguna.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_home_pengguna.setLabel("Pengguna");
        button_home_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_home_penggunaActionPerformed(evt);
            }
        });

        button_pembayaran_home.setBackground(new java.awt.Color(255, 51, 0));
        button_pembayaran_home.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_pembayaran_home.setLabel("Pembelian");
        button_pembayaran_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pembayaran_homeActionPerformed(evt);
            }
        });

        button_home_barang.setBackground(new java.awt.Color(255, 51, 0));
        button_home_barang.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_home_barang.setLabel("Barang");
        button_home_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_home_barangActionPerformed(evt);
            }
        });

        button_home_pengaturan.setBackground(new java.awt.Color(255, 51, 0));
        button_home_pengaturan.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_home_pengaturan.setLabel("Pengaturan");
        button_home_pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_home_pengaturanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(button_home_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(button_pembayaran_home, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(button_home_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button_home_pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .addComponent(panel_home_header, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addComponent(panel_home_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_home_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pembayaran_home, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_home_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_home_pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 429, Short.MAX_VALUE))
        );

        tab_holder.addTab("Home", panel_home);
        panel_home.getAccessibleContext().setAccessibleName("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );

        tab_holder.getAccessibleContext().setAccessibleName("tabHolder");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_home_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_home_penggunaActionPerformed
        // TODO add your handling code here:
        JPanel panel_pengguna = new JPanel(new BorderLayout());

        JPanel panel_title = new JPanel();
        panel_title.setBackground(new Color(238, 77, 45));
        panel_title.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        panel_title.setPreferredSize(new Dimension(450, 600));
        panel_pengguna.add(panel_title, BorderLayout.WEST);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.CENTER;
        gbc.anchor = GridBagConstraints.CENTER;
        JLabel label_pengguna = new JLabel();
        label_pengguna.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        label_pengguna.setForeground(new Color(255, 255, 255));
        label_pengguna.setText("PENGGUNA");
        panel_title.setLayout(new GridBagLayout());
        panel_title.add(label_pengguna,gbc);

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.CENTER;
        gbc.anchor = GridBagConstraints.PAGE_START;

        JPanel panel_context = new JPanel();
        panel_context.setBackground(new Color(255, 255, 255));
        panel_context.setLayout(new GridBagLayout());
        panel_context.setPreferredSize(new Dimension(540, 600));
        panel_pengguna.add(panel_context, BorderLayout.EAST);

        GridBagConstraints gbc1 = new GridBagConstraints();
        gbc1.gridx = 0;
        gbc1.gridy = 0;
        gbc1.weightx = 1.0;
        gbc1.weighty = 1.0;
        gbc1.fill = GridBagConstraints.CENTER;
        gbc1.anchor = GridBagConstraints.CENTER;
        gbc1.insets = new Insets(10, 0, 0, 0);

        JLabel label_daftar_pengguna = new JLabel();
        label_daftar_pengguna.setFont(new java.awt.Font("Arial", 0, 20));
        label_daftar_pengguna.setText("Daftar Pengguna");
        label_daftar_pengguna.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_daftar_pengguna, gbc1);

        GridBagConstraints gbc2 = new GridBagConstraints();
        gbc2.gridx = 0;
        gbc2.gridy = 1;
        gbc2.weightx = 1.0;
        gbc2.weighty = 1.0;
        gbc2.fill = GridBagConstraints.CENTER;
        gbc2.anchor = GridBagConstraints.CENTER;
        gbc2.insets = new Insets(10, 0, 0, 0);

        JLabel label_nama = new JLabel();
        label_nama.setText("Nama");
        panel_context.add(label_nama, gbc2);

        GridBagConstraints gbc3 = new GridBagConstraints();
        gbc3.gridx = 0;
        gbc3.gridy = 2;
        gbc3.weightx = 1.0;
        gbc3.weighty = 1.0;
        gbc3.fill = GridBagConstraints.CENTER;
        gbc3.anchor = GridBagConstraints.CENTER;
        gbc3.insets = new Insets(10, 0, 0, 0);

        TextField textField_nama = new TextField();
        textField_nama.setColumns(20);
        textField_nama.setBackground(new java.awt.Color(153, 153, 153));
        textField_nama.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_nama, gbc3);
                
        GridBagConstraints gbc4 = new GridBagConstraints();
        gbc4.gridx = 0;
        gbc4.gridy = 3;
        gbc4.weightx = 1.0;
        gbc4.weighty = 1.0;
        gbc4.fill = GridBagConstraints.CENTER;
        gbc4.anchor = GridBagConstraints.CENTER;
        gbc4.insets = new Insets(10, 0, 0, 0);
        
        JLabel label_notelp = new JLabel();
        label_notelp.setText("Nomor Telepon");
        panel_context.add(label_notelp, gbc4);
        
        GridBagConstraints gbc5 = new GridBagConstraints();
        gbc5.gridx = 0;
        gbc5.gridy = 4;
        gbc5.weightx = 1.0;
        gbc5.weighty = 1.0;
        gbc5.fill = GridBagConstraints.CENTER;
        gbc5.anchor = GridBagConstraints.CENTER;
        gbc5.insets = new Insets(10, 0, 0, 0);
        
        TextField textField_notelp = new TextField();
        textField_notelp.setColumns(20);
        textField_notelp.setBackground(new java.awt.Color(153, 153, 153));
        textField_notelp.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_notelp, gbc5);
        
        GridBagConstraints gbc6 = new GridBagConstraints();
        gbc6.gridx = 0;
        gbc6.gridy = 5;
        gbc6.weightx = 1.0;
        gbc6.weighty = 1.0;
        gbc6.fill = GridBagConstraints.CENTER;
        gbc6.anchor = GridBagConstraints.CENTER;
        gbc6.insets = new Insets(10, 0, 0, 0);
        
        Checkbox checkbox_VIP = new Checkbox();
        checkbox_VIP.setLabel("VIP");
        panel_context.add(checkbox_VIP, gbc6);
        
        GridBagConstraints gbc7 = new GridBagConstraints();
        gbc7.gridx = 0;
        gbc7.gridy = 6;
        gbc7.weightx = 1.0;
        gbc7.weighty = 1.0;
        gbc7.fill = GridBagConstraints.CENTER;
        gbc7.anchor = GridBagConstraints.CENTER;
        gbc7.insets = new Insets(10, 0, 0, 0);
        
        Checkbox checkbox_Member = new Checkbox();
        checkbox_Member.setLabel("Member");
        panel_context.add(checkbox_Member, gbc7);
        
        GridBagConstraints gbc8 = new GridBagConstraints();
        gbc8.gridx = 0;
        gbc8.gridy = 7;
        gbc8.weightx = 1.0;
        gbc8.weighty = 1.0;
        gbc8.fill = GridBagConstraints.CENTER;
        gbc8.anchor = GridBagConstraints.CENTER;
        gbc8.insets = new Insets(10, 0, 0, 0);
        
        JButton button_submit = new JButton();
        button_submit.setPreferredSize(new Dimension(100,50));
        button_submit.setBackground(new java.awt.Color(255, 0, 0));
        button_submit.setText("Submit");
        button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        panel_context.add(button_submit, gbc8);
        
        GridBagConstraints gbc9 = new GridBagConstraints();
        gbc9.gridx = 0;
        gbc9.gridy = 8;
        gbc9.weightx = 1.0;
        gbc9.weighty = 1.0;
        gbc9.fill = GridBagConstraints.CENTER;
        gbc9.anchor = GridBagConstraints.CENTER;
        gbc9.insets = new Insets(10, 0, 0, 0);
        
        JButton button_update_pengguna = new JButton();
        button_update_pengguna.setPreferredSize(new Dimension(150,50));
        button_update_pengguna.setBackground(new java.awt.Color(255, 51, 51));
        button_update_pengguna.setText("Update Pengguna");
        button_update_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panel_title.removeAll();
                panel_title.revalidate();
                panel_title.repaint();
                panel_context.removeAll();
                panel_context.revalidate();
                panel_context.repaint();

                GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridx = 0;
                gbc.gridy = 0;
                gbc.weightx = 1.0;
                gbc.weighty = 1.0;
                gbc.fill = GridBagConstraints.CENTER;
                gbc.anchor = GridBagConstraints.CENTER;

                JLabel label_update_pengguna = new JLabel();
                label_update_pengguna.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
                label_update_pengguna.setForeground(new Color(255, 255, 255));
                label_update_pengguna.setText("<html>UPDATE <br> PENGGUNA</html>");
                panel_title.setLayout(new GridBagLayout());
                panel_title.add(label_update_pengguna,gbc);

                gbc.gridx = 0;
                gbc.gridy = 0;
                gbc.weightx = 1.0;
                gbc.weighty = 1.0;
                gbc.fill = GridBagConstraints.CENTER;
                gbc.anchor = GridBagConstraints.PAGE_START;

                panel_context.setLayout(new GridBagLayout());

                GridBagConstraints gbc1 = new GridBagConstraints();
                gbc1.gridx = 0;
                gbc1.gridy = 0;
                gbc1.weightx = 1.0;
                gbc1.weighty = 0.2;
                gbc1.fill = GridBagConstraints.CENTER;
                gbc1.anchor = GridBagConstraints.CENTER;
                gbc1.insets = new Insets(2, 0, 0, 0);

                JLabel label_nama_up = new JLabel();
                label_nama_up.setFont(new java.awt.Font("Arial", 0, 15));
                label_nama_up.setText("Nama");
                label_nama_up.setHorizontalAlignment(JLabel.CENTER);
                panel_context.add(label_nama_up, gbc1);

                GridBagConstraints gbc2 = new GridBagConstraints();
                gbc2.gridx = 0;
                gbc2.gridy = 1;
                gbc2.weightx = 1.0;
                gbc2.weighty = 0.1;
                gbc2.fill = GridBagConstraints.CENTER;
                gbc2.anchor = GridBagConstraints.CENTER;
                gbc2.insets = new Insets(2, 0, 0, 0);

                TextField textField_nama_up = new TextField();
                textField_nama_up.setColumns(20);
                textField_nama_up.setBackground(new java.awt.Color(153, 153, 153));
                textField_nama_up.setFont(new java.awt.Font("Arial", 0, 14));
                panel_context.add(textField_nama_up, gbc2);

                GridBagConstraints gbc3 = new GridBagConstraints();
                gbc3.gridx = 0;
                gbc3.gridy = 2;
                gbc3.weightx = 1.0;
                gbc3.weighty = 0.2;
                gbc3.fill = GridBagConstraints.CENTER;
                gbc3.anchor = GridBagConstraints.CENTER;
                gbc3.insets = new Insets(2, 0, 0, 0);

                JButton button_update = new JButton();
                button_update.setBackground(new java.awt.Color(255, 0, 0));
                button_update.setText("Update");
                button_update.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                    }
                });
                panel_context.add(button_update, gbc3);
            }
        });
        panel_context.add(button_update_pengguna, gbc9);
        
        tab_holder.addTab("Pengguna", panel_pengguna);
        tab_holder.setSelectedIndex(tab_holder.getTabCount()-1);
    }//GEN-LAST:event_button_home_penggunaActionPerformed

    private void button_pembayaran_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pembayaran_homeActionPerformed
        JPanel panel_pembelian = new JPanel(new BorderLayout());

        tab_holder.addTab("Pembelian", panel_pembelian);
        tab_holder.setSelectedIndex(tab_holder.getTabCount()-1);
    }//GEN-LAST:event_button_pembayaran_homeActionPerformed

    private void button_home_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_home_barangActionPerformed
        // TODO add your handling code here:
        JPanel panel_barang = new JPanel(new BorderLayout());

        JPanel panel_title = new JPanel();
        panel_title.setBackground(new Color(238, 77, 45));
        panel_title.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        panel_title.setPreferredSize(new Dimension(450, 600));
        panel_barang.add(panel_title, BorderLayout.WEST);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.CENTER;
        gbc.anchor = GridBagConstraints.CENTER;
        JLabel label_pengguna = new JLabel();
        label_pengguna.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        label_pengguna.setForeground(new Color(255, 255, 255));
        label_pengguna.setText("BARANG");
        panel_title.setLayout(new GridBagLayout());
        panel_title.add(label_pengguna,gbc);

        JPanel panel_context = new JPanel();
        panel_context.setBackground(new Color(255, 255, 255));
        panel_context.setLayout(new GridBagLayout());
        panel_context.setPreferredSize(new Dimension(540, 600));
        panel_barang.add(panel_context, BorderLayout.EAST);

        GridBagConstraints gbc1 = new GridBagConstraints();
        gbc1.gridx = 0;
        gbc1.gridy = 0;
        gbc1.weightx = 1.0;
        gbc1.weighty = 0.1;
        gbc1.fill = GridBagConstraints.CENTER;
        gbc1.anchor = GridBagConstraints.CENTER;
        gbc1.insets = new Insets(10, 0, 0, 0);

        JLabel label_nama_barang = new JLabel();
        label_nama_barang.setFont(new java.awt.Font("Arial", 0, 15));
        label_nama_barang.setText("Nama barang");
        label_nama_barang.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_nama_barang, gbc1);

        GridBagConstraints gbc2 = new GridBagConstraints();
        gbc2.gridx = 0;
        gbc2.gridy = 1;
        gbc2.weightx = 1.0;
        gbc2.weighty = 0.1;
        gbc2.fill = GridBagConstraints.CENTER;
        gbc2.anchor = GridBagConstraints.CENTER;
        gbc2.insets = new Insets(10, 0, 0, 0);

        TextField textField_nama_barang = new TextField();
        textField_nama_barang.setColumns(20);
        textField_nama_barang.setBackground(new java.awt.Color(153, 153, 153));
        textField_nama_barang.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_nama_barang, gbc2);

        GridBagConstraints gbc3 = new GridBagConstraints();
        gbc3.gridx = 0;
        gbc3.gridy = 2;
        gbc3.weightx = 1.0;
        gbc3.weighty = 0.1;
        gbc3.fill = GridBagConstraints.CENTER;
        gbc3.anchor = GridBagConstraints.CENTER;
        gbc3.insets = new Insets(10, 0, 0, 0);

        JLabel label_stok = new JLabel();
        label_stok.setFont(new java.awt.Font("Arial", 0, 15));
        label_stok.setText("Stok");
        label_stok.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_stok, gbc3);

        GridBagConstraints gbc4 = new GridBagConstraints();
        gbc4.gridx = 0;
        gbc4.gridy = 3;
        gbc4.weightx = 1.0;
        gbc4.weighty = 0.1;
        gbc4.fill = GridBagConstraints.CENTER;
        gbc4.anchor = GridBagConstraints.CENTER;
        gbc4.insets = new Insets(10, 0, 0, 0);

        TextField textField_stok = new TextField();
        textField_stok.setColumns(20);
        textField_stok.setBackground(new java.awt.Color(153, 153, 153));
        textField_stok.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_stok, gbc4);

        GridBagConstraints gbc5 = new GridBagConstraints();
        gbc5.gridx = 0;
        gbc5.gridy = 4;
        gbc5.weightx = 1.0;
        gbc5.weighty = 0.1;
        gbc5.fill = GridBagConstraints.CENTER;
        gbc5.anchor = GridBagConstraints.CENTER;
        gbc5.insets = new Insets(10, 0, 0, 0);

        JLabel label_harga_barang = new JLabel();
        label_harga_barang.setFont(new java.awt.Font("Arial", 0, 15));
        label_harga_barang.setText("Harga barang");
        label_harga_barang.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_harga_barang, gbc5);

        GridBagConstraints gbc6 = new GridBagConstraints();
        gbc6.gridx = 0;
        gbc6.gridy = 5;
        gbc6.weightx = 1.0;
        gbc6.weighty = 0.1;
        gbc6.fill = GridBagConstraints.CENTER;
        gbc6.anchor = GridBagConstraints.CENTER;
        gbc6.insets = new Insets(10, 0, 0, 0);

        TextField textField_harga_barang = new TextField();
        textField_harga_barang.setColumns(20);
        textField_harga_barang.setBackground(new java.awt.Color(153, 153, 153));
        textField_harga_barang.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_harga_barang, gbc6);

        GridBagConstraints gbc7 = new GridBagConstraints();
        gbc7.gridx = 0;
        gbc7.gridy = 6;
        gbc7.weightx = 1.0;
        gbc7.weighty = 0.1;
        gbc7.fill = GridBagConstraints.CENTER;
        gbc7.anchor = GridBagConstraints.CENTER;
        gbc7.insets = new Insets(10, 0, 0, 0);

        JLabel label_harga_beli = new JLabel();
        label_harga_beli.setFont(new java.awt.Font("Arial", 0, 15));
        label_harga_beli.setText("Harga beli barang");
        label_harga_beli.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_harga_beli, gbc7);

        GridBagConstraints gbc8 = new GridBagConstraints();
        gbc8.gridx = 0;
        gbc8.gridy = 7;
        gbc8.weightx = 1.0;
        gbc8.weighty = 0.1;
        gbc8.fill = GridBagConstraints.CENTER;
        gbc8.anchor = GridBagConstraints.CENTER;
        gbc8.insets = new Insets(10, 0, 0, 0);

        TextField textField_harga_beli = new TextField();
        textField_harga_beli.setColumns(20);
        textField_harga_beli.setBackground(new java.awt.Color(153, 153, 153));
        textField_harga_beli.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_harga_beli, gbc8);

        GridBagConstraints gbc9 = new GridBagConstraints();
        gbc9.gridx = 0;
        gbc9.gridy = 8;
        gbc9.weightx = 1.0;
        gbc9.weighty = 0.1;
        gbc9.fill = GridBagConstraints.CENTER;
        gbc9.anchor = GridBagConstraints.CENTER;
        gbc9.insets = new Insets(10, 0, 0, 0);

        JLabel label_kategori = new JLabel();
        label_kategori.setFont(new java.awt.Font("Arial", 0, 15));
        label_kategori.setText("Kategori");
        label_kategori.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_kategori, gbc9);

        GridBagConstraints gbc10 = new GridBagConstraints();
        gbc10.gridx = 0;
        gbc10.gridy = 9;
        gbc10.weightx = 1.0;
        gbc10.weighty = 0.1;
        gbc10.fill = GridBagConstraints.CENTER;
        gbc10.anchor = GridBagConstraints.CENTER;
        gbc10.insets = new Insets(10, 0, 0, 0);

        TextField textField_kategori = new TextField();
        textField_kategori.setColumns(20);
        textField_kategori.setBackground(new java.awt.Color(153, 153, 153));
        textField_kategori.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_kategori, gbc10);

        GridBagConstraints gbc11 = new GridBagConstraints();
        gbc11.gridx = 0;
        gbc11.gridy = 10;
        gbc11.weightx = 1.0;
        gbc11.weighty = 0.1;
        gbc11.fill = GridBagConstraints.CENTER;
        gbc11.anchor = GridBagConstraints.CENTER;
        gbc11.insets = new Insets(10, 0, 0, 0);

        JLabel label_gambar = new JLabel();
        label_gambar.setFont(new java.awt.Font("Arial", 0, 15));
        label_gambar.setText("Gambar");
        label_gambar.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_gambar, gbc11);

        GridBagConstraints gbc12 = new GridBagConstraints();
        gbc12.gridx = 0;
        gbc12.gridy = 11;
        gbc12.weightx = 1.0;
        gbc12.weighty = 0.1;
        gbc12.fill = GridBagConstraints.CENTER;
        gbc12.anchor = GridBagConstraints.CENTER;
        gbc12.insets = new Insets(10, 0, 0, 0);

        TextField textField_gambar = new TextField();
        textField_gambar.setColumns(20);
        textField_gambar.setBackground(new java.awt.Color(153, 153, 153));
        textField_gambar.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_gambar, gbc12);

        GridBagConstraints gbc13 = new GridBagConstraints();
        gbc13.gridx = 0;
        gbc13.gridy = 12;
        gbc13.weightx = 1.0;
        gbc13.weighty = 0.1;
        gbc13.fill = GridBagConstraints.CENTER;
        gbc13.anchor = GridBagConstraints.CENTER;
        gbc13.insets = new Insets(10, 0, 0, 0);

        JButton button_submit = new JButton();
        button_submit.setPreferredSize(new Dimension(100,50));
        button_submit.setBackground(new java.awt.Color(255, 0, 0));
        button_submit.setText("Submit");
        button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        panel_context.add(button_submit, gbc13);

        tab_holder.addTab("Barang", panel_barang);
        tab_holder.setSelectedIndex(tab_holder.getTabCount()-1);

    }//GEN-LAST:event_button_home_barangActionPerformed

    private void button_home_pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_home_pengaturanActionPerformed
        // TODO add your handling code here:
        JPanel panel_pengaturan = new JPanel(new BorderLayout());
        JPanel panel_title = new JPanel();
        panel_title.setBackground(new Color(238, 77, 45));
        panel_title.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        panel_title.setPreferredSize(new Dimension(450, 600));
        panel_pengaturan.add(panel_title, BorderLayout.WEST);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.CENTER;
        gbc.anchor = GridBagConstraints.CENTER;
        JLabel label_penaturan = new JLabel();
        label_penaturan.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        label_penaturan.setForeground(new Color(255, 255, 255));
        label_penaturan.setText("PENGATURAN");
        panel_title.setLayout(new GridBagLayout());
        panel_title.add(label_penaturan,gbc);

        JPanel panel_context = new JPanel();
        panel_context.setBackground(new Color(255, 255, 255));
        panel_context.setLayout(new GridBagLayout());
        panel_context.setPreferredSize(new Dimension(540, 600));
        panel_pengaturan.add(panel_context, BorderLayout.EAST);

        GridBagConstraints gbc1 = new GridBagConstraints();
        gbc1.gridx = 0;
        gbc1.gridy = 0;
        gbc1.weightx = 1.0;
        gbc1.weighty = 1.0;
        gbc1.fill = GridBagConstraints.CENTER;
        gbc1.anchor = GridBagConstraints.CENTER;
        gbc1.insets = new Insets(10, 0, 0, 0);

        JLabel label_penyimpanan_file = new JLabel();
        label_penyimpanan_file.setFont(new java.awt.Font("Arial", 0, 20));
        label_penyimpanan_file.setText("Penyimpanan file");
        label_penyimpanan_file.setHorizontalAlignment(JLabel.CENTER);
        panel_context.add(label_penyimpanan_file, gbc1);

        GridBagConstraints gbc2 = new GridBagConstraints();
        gbc2.gridx = 0;
        gbc2.gridy = 1;
        gbc2.weightx = 1.0;
        gbc2.weighty = 1.0;
        gbc2.fill = GridBagConstraints.CENTER;
        gbc2.anchor = GridBagConstraints.CENTER;
        gbc2.insets = new Insets(10, 0, 0, 0);

        TextField textField_penyimpanan = new TextField();
        textField_penyimpanan.setColumns(20);
        textField_penyimpanan.setBackground(new java.awt.Color(153, 153, 153));
        textField_penyimpanan.setFont(new java.awt.Font("Arial", 0, 14));
        panel_context.add(textField_penyimpanan, gbc2);

        GridBagConstraints gbc3 = new GridBagConstraints();
        gbc3.gridx = 0;
        gbc3.gridy = 2;
        gbc3.weightx = 1.0;
        gbc3.weighty = 1.0;
        gbc3.fill = GridBagConstraints.CENTER;
        gbc3.anchor = GridBagConstraints.CENTER;
        gbc3.insets = new Insets(10, 0, 0, 0);

        JButton button_submit = new JButton();
        button_submit.setPreferredSize(new Dimension(100,50));
        button_submit.setBackground(new java.awt.Color(238, 77, 45));
        button_submit.setText("Change");
        button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        panel_context.add(button_submit, gbc3);

        GridBagConstraints gbc4 = new GridBagConstraints();
        gbc4.gridx = 0;
        gbc4.gridy = 3;
        gbc4.weightx = 1.0;
        gbc4.weighty = 1.0;
        gbc4.fill = GridBagConstraints.CENTER;
        gbc4.anchor = GridBagConstraints.CENTER;
        gbc4.insets = new Insets(10, 0, 0, 0);

        JButton button_plugin = new JButton();
        button_plugin.setPreferredSize(new Dimension(200,100));
        button_plugin.setBackground(new java.awt.Color(255, 255, 255));
        button_plugin.setText("Plugin");
        button_plugin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        panel_context.add(button_plugin, gbc4);
        tab_holder.addTab("Pengaturan", panel_pengaturan);
        System.out.println(tab_holder.getTabCount());
        tab_holder.setSelectedIndex(tab_holder.getTabCount()-1);
    }//GEN-LAST:event_button_home_pengaturanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_home_barang;
    private java.awt.Button button_home_pengaturan;
    private java.awt.Button button_home_pengguna;
    private java.awt.Button button_pembayaran_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_time;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_home_header;
    private javax.swing.JTabbedPane tab_holder;
    // End of variables declaration//GEN-END:variables
}
